# ===============================
# Spring Configuration
# ===============================
spring.application.name=naillian-backend
server.port=8080
server.address=0.0.0.0

# ===============================
# Logging Configuration
# ===============================
logging.level.org.springframework=INFO
logging.level.com.naillian=DEBUG

# ===============================
# R2DBC Database Configuration (MariaDB)
# ===============================
spring.r2dbc.url=r2dbc:mariadb://host:port/dbname
spring.r2dbc.username=
spring.r2dbc.password=

# ===============================
# Redis
# ===============================
spring.data.redis.host=redis
spring.data.redis.port=6379

# ===============================
# JWT Key
# ===============================
jwt.secret=JWT_SECRET_KEY

# ===============================
# AWS S3 Configuration
# ===============================
cloud.aws.region.static=ap-northeast-2
cloud.aws.s3.bucket=bucketname
cloud.aws.s3.endpoint=https://bucketname.s3.amazonaws.com
cloud.aws.s3.upload-root=/nail/

# ===============================
# CloudFront Configuration
# ===============================
cloudfront.domain=
cloudfront.cdn=
cloudfront.cache-policy=default
cloudfront.allowed-methods=GET,HEAD,OPTIONS

# ===============================
# OAuth: Kakao
# ===============================
kakao.auth.rest-api-key=
kakao.auth.javascript-key=
kakao.auth.admin-key=
kakao.auth.native-app-key=
kakao.auth.callback-url=https://example.com/path/to/callback
