name: Build and Deploy docker image
on:
  push:
    branches:
      - dev

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        run: |
          docker buildx create --bootstrap --use

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        run: |
          docker buildx build \
            --platform linux/arm64,linux/amd64 \
            --tag ghcr.io/${{ github.repository }}:dev \
            --tag ghcr.io/${{ github.repository }}:$(git rev-parse --short HEAD) \
            --push .

  trigger-deploy-infra:
    runs-on: ubuntu-latest
    needs:
      - build-and-push-docker
    steps:
      - name: Dispatch event
        run: gh api /repos/snail-official/nailian-iac/dispatches -f event_type='restart-backend-dev'
        env:
          GH_TOKEN: ${{ secrets.GH_TRIGGER_TOKEN }}
